-- MySQL Script generated by MySQL Workbench
-- Fri Mar 18 10:43:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema unidad2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema unidad2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `unidad2` DEFAULT CHARACTER SET utf8 ;
USE `unidad2` ;

-- -----------------------------------------------------
-- Table `unidad2`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unidad2`.`usuario` (
  `Codigo` VARCHAR(15) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `TipoUsuario` VARCHAR(15) NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
